### ISSUE TITLE
How to tune the parameters for aerial simulator

### ISSUE THREAD

**Issue by nuyhead-hwang** [caochao39/tare_planner#14]
Hello, thank you for sharing your great work.

Cloud you explain how to tune the parameters and code of  'tare_planner' to work with mav or aerial simulator like your aerial_navigation_develop ment_envrionment ? 

We tried to tune viewpoint_manaver/numzer_z, viewpoint_manaver/resolution_z, kConnectivtyHeightDiffThr parameter for aerial simulator, but it didn't seem to work.

**Comment by Chic-J** [comment]
hello，I need the aerial simulator. do u fix it？

**Comment by caochao39** [comment]
Hello, the existing code is tailored for ground vehicles. We've withheld the aerial version due to possible commercial implications. However, you're welcome to adapt the code for aerial use. Please note, I might not offer guidance on this, given the significant differences between ground and aerial vehicle codebases.
